services:
  - type: web
    name: screensmart-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: GMAIL_EMAIL
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
